---
- name: Install Wireguard server and tools
  ansible.builtin.package:
    name:
      - wireguard
      - qrencode

- name: Generate Wireguard server key
  ansible.builtin.shell:
    executable: /bin/bash
    chdir: /etc/wireguard
    cmd: |
      set -e -o pipefail
      wg genkey | tee server.key | wg pubkey > server.key.pub
    creates: /etc/wireguard/server.key

- name: Set permissions for server key
  ansible.builtin.file:
    path: '/etc/wireguard/{{ item }}'
    owner: root
    group: root
    mode: '0400'
  loop:
    - server.key
    - server.key.pub

- name: Initialize Wireguard server config
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/
    owner: root
    group: root
    mode: '0640'
    force: false
  notify: Restart Wireguard service

- name: Read server private key
  ansible.builtin.slurp:
    src: /etc/wireguard/server.key
  register: server_key_slurp

- name: Set server configuration values
  ansible.builtin.replace:
    path: /etc/wireguard/wg0.conf
    regexp: '%{{ item.key }}%'
    replace: '{{ item.value }}'
  loop:
    - key: SERVER_PRIVATE_KEY
      value: '{{ server_key_slurp.content | ansible.builtin.b64decode }}'
    - key: OUT_INTERFACE
      value: '{{ ansible_default_ipv4.interface | default("eth0") }}'
  loop_control:
    label: '{{ item.key }}'
  notify: Restart Wireguard service

- name: Enable IP forwarding
  ansible.builtin.copy:
    content: |
      # Enable IP forwarding for Wireguard
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
    dest: /etc/sysctl.d/99-wireguard.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload system config

- name: Open Wireguard port
  community.general.ufw:
    comment: "Wireguard server"
    rule: allow
    port: 51820
    proto: udp

- name: Create clients configuration directory
  ansible.builtin.file:
    path: /etc/wireguard/clients
    owner: root
    group: root
    mode: '0750'
    state: directory

- name: Deploy client config creation script
  ansible.builtin.copy:
    src: wg-create-client
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: '0750'
    force: true

- name: Enable Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0.service
    enabled: true
