---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Apply role
      ansible.builtin.import_role:
        name: wsmirnow.wireguard
