---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Wireguard service state
      check_mode: true
      ansible.builtin.service:
        name: wg-quick@wg0.service
        state: started
      register: wg_service_running

    - name: Verify Wireguard service is running
      ansible.builtin.assert:
        that:
          - wg_service_running.changed == False
          - wg_service_running.state == "started"
